version: '3.7'

volumes:
  library.db.volume:
    name: library.db.volume

services:
  db:
    image: mysql:5.7.21
    container_name: library.db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - library.db.volume:/var/lib/mysql
      - ./etc/sql:/docker-entrypoint-initdb.d

  web:
    build: ./etc/web
    container_name: library.web
    command: >
      bash -c "sh /wait.sh db root password sh /run.sh"
    volumes:
      - ./library:/app
      - ./static:/static
    ports:
      - 8000:8000  # app
      - 10080:8888 # jupyter
    depends_on:
      - db
      - redis

  redis:
    image: redis:4.0.10
    ports:
    - 6379:6379
